config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/ayuda'

  get 'static_pages/home'
  get 'static_pages/ayuda'
  get 'static_pages/acerca'
  

  resources :disfrazs

  resources :categoria

  resources :clientes

  resources :vendedors

  resources :transicion_arriendos

  resources :arriendo_estados

  resources :detalle_arriendos

  resources :arriendos

  resources :multa

  resources :nota_de_venta

  resources :detalle_devolucions

  resources :devolucions

  resources :vendedor_estados

  resources :transicion_est_vendedors

  resources :pedidos_detalles

  resources :transicion_est_pedidos

  resources :pedido_estados

  resources :pedidos

  resources :auditoria

  resources :parametro_sistemas

  resources :transicion_est_clientes

  resources :cliente_estados

  resources :transicion_est_ejemplars

  resources :ejemplar_estados

  resources :ejemplars

  

  root 'disfrazs#index'

end

app/models/arriendo.rb
class Arriendo < ActiveRecord::Base
end

app/models/arriendo_estado.rb
class ArriendoEstado < ActiveRecord::Base
end

app/models/auditorium.rb
class Auditorium < ActiveRecord::Base
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	has_many :pedidos
end

app/models/cliente_estado.rb
class ClienteEstado < ActiveRecord::Base
end

app/models/detalle_arriendo.rb
class DetalleArriendo < ActiveRecord::Base
end

app/models/devolucion.rb
class Devolucion < ActiveRecord::Base
end

app/models/disfraz.rb
class Disfraz < ActiveRecord::Base
end

app/models/ejemplar.rb
class Ejemplar < ActiveRecord::Base
end

app/models/ejemplar_estado.rb
class EjemplarEstado < ActiveRecord::Base
end

app/models/multum.rb
class Multum < ActiveRecord::Base
end

app/models/nota_de_ventum.rb
class NotaDeVentum < ActiveRecord::Base
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
	belongs_to :cliente	
	validates :estado_pedido, presence: true
	validates_date :fecha_pedido,  date: { after: Proc.new { Time.now + 3.day}, allow_blank: false}

end

app/models/pedido_estado.rb
class PedidoEstado < ActiveRecord::Base
end

app/models/pedidos_detalle.rb
class PedidosDetalle < ActiveRecord::Base
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
end

app/models/vendedor_estado.rb
class VendedorEstado < ActiveRecord::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'El cliente fue satisfactoriamente creado.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'El cliente fue satisfactoriamente actualizado.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'El cliente fue satisfactoriamente eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:id_cliente, :nombre_cliente, :apellido_cliente, :rut_cliente, :correo_cliente, :direccion_cliente, :telefono_cliente, :estado_cliente, :password_cliente)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/disfrazs_helper.rb
module DisfrazsHelper
end

app/helpers/multa_helper.rb
module MultaHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_cliente %><br>
    <%= f.number_field :id_cliente %>
  </div>
  <div class="field">
    <%= f.label :nombre_cliente %><br>
    <%= f.text_field :nombre_cliente %>
  </div>
  <div class="field">
    <%= f.label :apellido_cliente %><br>
    <%= f.text_field :apellido_cliente %>
  </div>
  <div class="field">
    <%= f.label :rut_cliente %><br>
    <%= f.number_field :rut_cliente %>
  </div>
  <div class="field">
    <%= f.label :correo_cliente %><br>
    <%= f.text_field :correo_cliente %>
  </div>
  <div class="field">
    <%= f.label :direccion_cliente %><br>
    <%= f.text_field :direccion_cliente %>
  </div>
  <div class="field">
    <%= f.label :telefono_cliente %><br>
    <%= f.number_field :telefono_cliente %>
  </div>
  <div class="field">
    <%= f.label :estado_cliente %><br>
    <%= f.text_field :estado_cliente %>
  </div>
  <div class="field">
    <%= f.label :password_cliente %><br>
    <%= f.text_field :password_cliente %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <thead>
    <tr>
      <th>Id cliente</th>
      <th>Nombre cliente</th>
      <th>Apellido cliente</th>
      <th>Rut cliente</th>
      <th>Correo cliente</th>
      <th>Direccion cliente</th>
      <th>Telefono cliente</th>
      <th>Estado cliente</th>
      <th>Password cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.id_cliente %></td>
        <td><%= cliente.nombre_cliente %></td>
        <td><%= cliente.apellido_cliente %></td>
        <td><%= cliente.rut_cliente %></td>
        <td><%= cliente.correo_cliente %></td>
        <td><%= cliente.direccion_cliente %></td>
        <td><%= cliente.telefono_cliente %></td>
        <td><%= cliente.estado_cliente %></td>
        <td><%= cliente.password_cliente %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id cliente:</strong>
  <%= @cliente.id_cliente %>
</p>

<p>
  <strong>Nombre cliente:</strong>
  <%= @cliente.nombre_cliente %>
</p>

<p>
  <strong>Apellido cliente:</strong>
  <%= @cliente.apellido_cliente %>
</p>

<p>
  <strong>Rut cliente:</strong>
  <%= @cliente.rut_cliente %>
</p>

<p>
  <strong>Correo cliente:</strong>
  <%= @cliente.correo_cliente %>
</p>

<p>
  <strong>Direccion cliente:</strong>
  <%= @cliente.direccion_cliente %>
</p>

<p>
  <strong>Telefono cliente:</strong>
  <%= @cliente.telefono_cliente %>
</p>

<p>
  <strong>Estado cliente:</strong>
  <%= @cliente.estado_cliente %>
</p>

<p>
  <strong>Password cliente:</strong>
  <%= @cliente.password_cliente %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>