config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/ayuda'

  get 'static_pages/home'
  get 'static_pages/ayuda'
  get 'static_pages/acerca'
  

  resources :disfrazs

  resources :categoria

  resources :clientes

  resources :vendedors

  resources :transicion_arriendos

  resources :arriendo_estados

  resources :detalle_arriendos

  resources :arriendos

  resources :multa

  resources :nota_de_venta

  resources :detalle_devolucions

  resources :devolucions

  resources :vendedor_estados

  resources :transicion_est_vendedors

  resources :pedidos_detalles

  resources :transicion_est_pedidos

  resources :pedido_estados

  resources :pedidos

  resources :auditoria

  resources :parametro_sistemas

  resources :transicion_est_clientes

  resources :cliente_estados

  resources :transicion_est_ejemplars

  resources :ejemplar_estados

  resources :ejemplars

  

  root 'disfrazs#index'

end

app/models/arriendo.rb
class Arriendo < ActiveRecord::Base
end

app/models/arriendo_estado.rb
class ArriendoEstado < ActiveRecord::Base
end

app/models/auditorium.rb
class Auditorium < ActiveRecord::Base
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	has_many :pedidos
end

app/models/cliente_estado.rb
class ClienteEstado < ActiveRecord::Base
end

app/models/devolucion.rb
class Devolucion < ActiveRecord::Base
end

app/models/disfraz.rb
class Disfraz < ActiveRecord::Base
end

app/models/ejemplar.rb
class Ejemplar < ActiveRecord::Base
end

app/models/ejemplar_estado.rb
class EjemplarEstado < ActiveRecord::Base
end

app/models/multum.rb
class Multum < ActiveRecord::Base
end

app/models/nota_de_ventum.rb
class NotaDeVentum < ActiveRecord::Base
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
	belongs_to :cliente	
	validates :estado_pedido, presence: true
	validates_date :fecha_pedido,  date: { after: Proc.new { Time.now + 3.day}, allow_blank: false}

end

app/models/pedido_estado.rb
class PedidoEstado < ActiveRecord::Base
end

app/models/pedidos_detalle.rb
class PedidosDetalle < ActiveRecord::Base
end

app/models/transicion_est_pedido.rb
class TransicionEstPedido < ActiveRecord::Base
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
end

app/models/vendedor_estado.rb
class VendedorEstado < ActiveRecord::Base
end

app/controllers/transicion_est_pedidos_controller.rb
class TransicionEstPedidosController < ApplicationController
  before_action :set_transicion_est_pedido, only: [:show, :edit, :update, :destroy]

  # GET /transicion_est_pedidos
  # GET /transicion_est_pedidos.json
  def index
    @transicion_est_pedidos = TransicionEstPedido.all
  end

  # GET /transicion_est_pedidos/1
  # GET /transicion_est_pedidos/1.json
  def show
  end

  # GET /transicion_est_pedidos/new
  def new
    @transicion_est_pedido = TransicionEstPedido.new
  end

  # GET /transicion_est_pedidos/1/edit
  def edit
  end

  # POST /transicion_est_pedidos
  # POST /transicion_est_pedidos.json
  def create
    @transicion_est_pedido = TransicionEstPedido.new(transicion_est_pedido_params)

    respond_to do |format|
      if @transicion_est_pedido.save
        format.html { redirect_to @transicion_est_pedido, notice: 'Transicion est pedido was successfully created.' }
        format.json { render :show, status: :created, location: @transicion_est_pedido }
      else
        format.html { render :new }
        format.json { render json: @transicion_est_pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transicion_est_pedidos/1
  # PATCH/PUT /transicion_est_pedidos/1.json
  def update
    respond_to do |format|
      if @transicion_est_pedido.update(transicion_est_pedido_params)
        format.html { redirect_to @transicion_est_pedido, notice: 'Transicion est pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @transicion_est_pedido }
      else
        format.html { render :edit }
        format.json { render json: @transicion_est_pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transicion_est_pedidos/1
  # DELETE /transicion_est_pedidos/1.json
  def destroy
    @transicion_est_pedido.destroy
    respond_to do |format|
      format.html { redirect_to transicion_est_pedidos_url, notice: 'Transicion est pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transicion_est_pedido
      @transicion_est_pedido = TransicionEstPedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transicion_est_pedido_params
      params.require(:transicion_est_pedido).permit(:est_ini_pedido, :est_fin_pedido)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/multa_helper.rb
module MultaHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/transicion_est_pedidos_helper.rb
module TransicionEstPedidosHelper
end

app/views/transicion_est_pedidos/_form.html.erb
<%= form_for(@transicion_est_pedido) do |f| %>
  <% if @transicion_est_pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transicion_est_pedido.errors.count, "error") %> prohibited this transicion_est_pedido from being saved:</h2>

      <ul>
      <% @transicion_est_pedido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :est_ini_pedido %><br>
    <%= f.text_field :est_ini_pedido %>
  </div>
  <div class="field">
    <%= f.label :est_fin_pedido %><br>
    <%= f.text_field :est_fin_pedido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transicion_est_pedidos/edit.html.erb
<h1>Editing transicion_est_pedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @transicion_est_pedido %> |
<%= link_to 'Back', transicion_est_pedidos_path %>

app/views/transicion_est_pedidos/index.html.erb
<h1>Listing transicion_est_pedidos</h1>

<table>
  <thead>
    <tr>
      <th>Est ini pedido</th>
      <th>Est fin pedido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transicion_est_pedidos.each do |transicion_est_pedido| %>
      <tr>
        <td><%= transicion_est_pedido.est_ini_pedido %></td>
        <td><%= transicion_est_pedido.est_fin_pedido %></td>
        <td><%= link_to 'Show', transicion_est_pedido %></td>
        <td><%= link_to 'Edit', edit_transicion_est_pedido_path(transicion_est_pedido) %></td>
        <td><%= link_to 'Destroy', transicion_est_pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transicion est pedido', new_transicion_est_pedido_path %>

app/views/transicion_est_pedidos/new.html.erb
<h1>New transicion_est_pedido</h1>

<%= render 'form' %>

<%= link_to 'Back', transicion_est_pedidos_path %>

app/views/transicion_est_pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Est ini pedido:</strong>
  <%= @transicion_est_pedido.est_ini_pedido %>
</p>

<p>
  <strong>Est fin pedido:</strong>
  <%= @transicion_est_pedido.est_fin_pedido %>
</p>

<%= link_to 'Edit', edit_transicion_est_pedido_path(@transicion_est_pedido) %> |
<%= link_to 'Back', transicion_est_pedidos_path %>