config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/ayuda'

  get 'static_pages/home'
  get 'static_pages/ayuda'
  get 'static_pages/acerca'
  

  resources :disfrazs

  resources :categoria

  resources :clientes

  resources :vendedors

  resources :transicion_arriendos

  resources :arriendo_estados

  resources :detalle_arriendos

  resources :arriendos

  resources :multa

  resources :nota_de_venta

  resources :detalle_devolucions

  resources :devolucions

  resources :vendedor_estados

  resources :transicion_est_vendedors

  resources :pedidos_detalles

  resources :transicion_est_pedidos

  resources :pedido_estados

  resources :pedidos

  resources :auditoria

  resources :parametro_sistemas

  resources :transicion_est_clientes

  resources :cliente_estados

  resources :transicion_est_ejemplars

  resources :ejemplar_estados

  resources :ejemplars

  

  root 'disfrazs#index'

end

app/models/arriendo.rb
class Arriendo < ActiveRecord::Base
end

app/models/arriendo_estado.rb
class ArriendoEstado < ActiveRecord::Base
end

app/models/auditorium.rb
class Auditorium < ActiveRecord::Base
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	has_many :pedidos
end

app/models/cliente_estado.rb
class ClienteEstado < ActiveRecord::Base
end

app/models/detalle_arriendo.rb
class DetalleArriendo < ActiveRecord::Base
end

app/models/devolucion.rb
class Devolucion < ActiveRecord::Base
end

app/models/disfraz.rb
class Disfraz < ActiveRecord::Base
end

app/models/ejemplar.rb
class Ejemplar < ActiveRecord::Base
end

app/models/ejemplar_estado.rb
class EjemplarEstado < ActiveRecord::Base
end

app/models/multum.rb
class Multum < ActiveRecord::Base
end

app/models/nota_de_ventum.rb
class NotaDeVentum < ActiveRecord::Base
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
	belongs_to :cliente	
	validates :estado_pedido, presence: true
	validates_date :fecha_pedido,  date: { after: Proc.new { Time.now + 3.day}, allow_blank: false}

end

app/models/pedido_estado.rb
class PedidoEstado < ActiveRecord::Base
end

app/models/pedidos_detalle.rb
class PedidosDetalle < ActiveRecord::Base
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
end

app/models/vendedor_estado.rb
class VendedorEstado < ActiveRecord::Base
end

app/controllers/disfrazs_controller.rb
class DisfrazsController < ApplicationController
  before_action :set_disfraz, only: [:show, :edit, :update, :destroy]

  # GET /disfrazs
  # GET /disfrazs.json
  def index
    @disfrazs = Disfraz.all
  end

  # GET /disfrazs/1
  # GET /disfrazs/1.json
  def show
  end

  # GET /disfrazs/new
  def new
    @disfraz = Disfraz.new
  end

  # GET /disfrazs/1/edit
  def edit
  end

  # POST /disfrazs
  # POST /disfrazs.json
  def create
    @disfraz = Disfraz.new(disfraz_params)

    respond_to do |format|
      if @disfraz.save
        format.html { redirect_to @disfraz, notice: 'Disfraz was successfully created.' }
        format.json { render :show, status: :created, location: @disfraz }
      else
        format.html { render :new }
        format.json { render json: @disfraz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disfrazs/1
  # PATCH/PUT /disfrazs/1.json
  def update
    respond_to do |format|
      if @disfraz.update(disfraz_params)
        format.html { redirect_to @disfraz, notice: 'Disfraz was successfully updated.' }
        format.json { render :show, status: :ok, location: @disfraz }
      else
        format.html { render :edit }
        format.json { render json: @disfraz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disfrazs/1
  # DELETE /disfrazs/1.json
  def destroy
    @disfraz.destroy
    respond_to do |format|
      format.html { redirect_to disfrazs_url, notice: 'Disfraz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disfraz
      @disfraz = Disfraz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disfraz_params
      params.require(:disfraz).permit(:id_disfraz, :categoria_disfraz, :stock_disfraz, :stock_disponible)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/disfrazs_helper.rb
module DisfrazsHelper
end

app/helpers/multa_helper.rb
module MultaHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/disfrazs/_form.html.erb
<%= form_for(@disfraz) do |f| %>
  <% if @disfraz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disfraz.errors.count, "error") %> prohibited this disfraz from being saved:</h2>

      <ul>
      <% @disfraz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_disfraz %><br>
    <%= f.number_field :id_disfraz %>
  </div>
  <div class="field">
    <%= f.label :categoria_disfraz %><br>
    <%= f.text_field :categoria_disfraz %>
  </div>
  <div class="field">
    <%= f.label :stock_disfraz %><br>
    <%= f.number_field :stock_disfraz %>
  </div>
  <div class="field">
    <%= f.label :stock_disponible %><br>
    <%= f.number_field :stock_disponible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disfrazs/edit.html.erb
<h1>Editing disfraz</h1>

<%= render 'form' %>

<%= link_to 'Show', @disfraz %> |
<%= link_to 'Back', disfrazs_path %>

app/views/disfrazs/index.html.erb
<h1>Listing disfrazs</h1>

<table>
  <thead>
    <tr>
      <th>Id disfraz</th>
      <th>Categoria disfraz</th>
      <th>Stock disfraz</th>
      <th>Stock disponible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disfrazs.each do |disfraz| %>
      <tr>
        <td><%= disfraz.id_disfraz %></td>
        <td><%= disfraz.categoria_disfraz %></td>
        <td><%= disfraz.stock_disfraz %></td>
        <td><%= disfraz.stock_disponible %></td>
        <td><%= link_to 'Show', disfraz %></td>
        <td><%= link_to 'Edit', edit_disfraz_path(disfraz) %></td>
        <td><%= link_to 'Destroy', disfraz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disfraz', new_disfraz_path %>

app/views/disfrazs/new.html.erb
<h1>New disfraz</h1>

<%= render 'form' %>

<%= link_to 'Back', disfrazs_path %>

app/views/disfrazs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id disfraz:</strong>
  <%= @disfraz.id_disfraz %>
</p>

<p>
  <strong>Categoria disfraz:</strong>
  <%= @disfraz.categoria_disfraz %>
</p>

<p>
  <strong>Stock disfraz:</strong>
  <%= @disfraz.stock_disfraz %>
</p>

<p>
  <strong>Stock disponible:</strong>
  <%= @disfraz.stock_disponible %>
</p>

<%= link_to 'Edit', edit_disfraz_path(@disfraz) %> |
<%= link_to 'Back', disfrazs_path %>