config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/ayuda'

  get 'static_pages/home'
  get 'static_pages/ayuda'
  get 'static_pages/acerca'
  

  resources :disfrazs

  resources :categoria

  resources :clientes

  resources :vendedors

  resources :transicion_arriendos

  resources :arriendo_estados

  resources :detalle_arriendos

  resources :arriendos

  resources :multa

  resources :nota_de_venta

  resources :detalle_devolucions

  resources :devolucions

  resources :vendedor_estados

  resources :transicion_est_vendedors

  resources :pedidos_detalles

  resources :transicion_est_pedidos

  resources :pedido_estados

  resources :pedidos

  resources :auditoria

  resources :parametro_sistemas

  resources :transicion_est_clientes

  resources :cliente_estados

  resources :transicion_est_ejemplars

  resources :ejemplar_estados

  resources :ejemplars

  

  root 'disfrazs#index'

end

app/models/arriendo.rb
class Arriendo < ActiveRecord::Base
end

app/models/arriendo_estado.rb
class ArriendoEstado < ActiveRecord::Base
end

app/models/auditorium.rb
class Auditorium < ActiveRecord::Base
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	has_many :pedidos
end

app/models/cliente_estado.rb
class ClienteEstado < ActiveRecord::Base
end

app/models/devolucion.rb
class Devolucion < ActiveRecord::Base
end

app/models/disfraz.rb
class Disfraz < ActiveRecord::Base
end

app/models/ejemplar.rb
class Ejemplar < ActiveRecord::Base
end

app/models/ejemplar_estado.rb
class EjemplarEstado < ActiveRecord::Base
end

app/models/multum.rb
class Multum < ActiveRecord::Base
end

app/models/nota_de_ventum.rb
class NotaDeVentum < ActiveRecord::Base
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
	belongs_to :cliente	
	validates :estado_pedido, presence: true
	validates_date :fecha_pedido,  date: { after: Proc.new { Time.now + 3.day}, allow_blank: false}

end

app/models/pedido_estado.rb
class PedidoEstado < ActiveRecord::Base
end

app/models/pedidos_detalle.rb
class PedidosDetalle < ActiveRecord::Base
end

app/models/transicion_arriendo.rb
class TransicionArriendo < ActiveRecord::Base
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
end

app/models/vendedor_estado.rb
class VendedorEstado < ActiveRecord::Base
end

app/controllers/transicion_arriendos_controller.rb
class TransicionArriendosController < ApplicationController
  before_action :set_transicion_arriendo, only: [:show, :edit, :update, :destroy]

  # GET /transicion_arriendos
  # GET /transicion_arriendos.json
  def index
    @transicion_arriendos = TransicionArriendo.all
  end

  # GET /transicion_arriendos/1
  # GET /transicion_arriendos/1.json
  def show
  end

  # GET /transicion_arriendos/new
  def new
    @transicion_arriendo = TransicionArriendo.new
  end

  # GET /transicion_arriendos/1/edit
  def edit
  end

  # POST /transicion_arriendos
  # POST /transicion_arriendos.json
  def create
    @transicion_arriendo = TransicionArriendo.new(transicion_arriendo_params)

    respond_to do |format|
      if @transicion_arriendo.save
        format.html { redirect_to @transicion_arriendo, notice: 'Transicion arriendo was successfully created.' }
        format.json { render :show, status: :created, location: @transicion_arriendo }
      else
        format.html { render :new }
        format.json { render json: @transicion_arriendo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transicion_arriendos/1
  # PATCH/PUT /transicion_arriendos/1.json
  def update
    respond_to do |format|
      if @transicion_arriendo.update(transicion_arriendo_params)
        format.html { redirect_to @transicion_arriendo, notice: 'Transicion arriendo was successfully updated.' }
        format.json { render :show, status: :ok, location: @transicion_arriendo }
      else
        format.html { render :edit }
        format.json { render json: @transicion_arriendo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transicion_arriendos/1
  # DELETE /transicion_arriendos/1.json
  def destroy
    @transicion_arriendo.destroy
    respond_to do |format|
      format.html { redirect_to transicion_arriendos_url, notice: 'Transicion arriendo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transicion_arriendo
      @transicion_arriendo = TransicionArriendo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transicion_arriendo_params
      params.require(:transicion_arriendo).permit(:est_ini_arriendo, :est_fin_arriendo)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/multa_helper.rb
module MultaHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/transicion_arriendos_helper.rb
module TransicionArriendosHelper
end

app/views/transicion_arriendos/_form.html.erb
<%= form_for(@transicion_arriendo) do |f| %>
  <% if @transicion_arriendo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transicion_arriendo.errors.count, "error") %> prohibited this transicion_arriendo from being saved:</h2>

      <ul>
      <% @transicion_arriendo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :est_ini_arriendo %><br>
    <%= f.text_field :est_ini_arriendo %>
  </div>
  <div class="field">
    <%= f.label :est_fin_arriendo %><br>
    <%= f.text_field :est_fin_arriendo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transicion_arriendos/edit.html.erb
<h1>Editing transicion_arriendo</h1>

<%= render 'form' %>

<%= link_to 'Show', @transicion_arriendo %> |
<%= link_to 'Back', transicion_arriendos_path %>

app/views/transicion_arriendos/index.html.erb
<h1>Listing transicion_arriendos</h1>

<table>
  <thead>
    <tr>
      <th>Est ini arriendo</th>
      <th>Est fin arriendo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transicion_arriendos.each do |transicion_arriendo| %>
      <tr>
        <td><%= transicion_arriendo.est_ini_arriendo %></td>
        <td><%= transicion_arriendo.est_fin_arriendo %></td>
        <td><%= link_to 'Show', transicion_arriendo %></td>
        <td><%= link_to 'Edit', edit_transicion_arriendo_path(transicion_arriendo) %></td>
        <td><%= link_to 'Destroy', transicion_arriendo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transicion arriendo', new_transicion_arriendo_path %>

app/views/transicion_arriendos/new.html.erb
<h1>New transicion_arriendo</h1>

<%= render 'form' %>

<%= link_to 'Back', transicion_arriendos_path %>

app/views/transicion_arriendos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Est ini arriendo:</strong>
  <%= @transicion_arriendo.est_ini_arriendo %>
</p>

<p>
  <strong>Est fin arriendo:</strong>
  <%= @transicion_arriendo.est_fin_arriendo %>
</p>

<%= link_to 'Edit', edit_transicion_arriendo_path(@transicion_arriendo) %> |
<%= link_to 'Back', transicion_arriendos_path %>